### ISSUE TITLE
Advancements tab displays prefixes incorrectly (missing textures, crashes w/ some other mods)

### ISSUE THREAD

**Issue by paperclone22** [MiningMark48/Prefixation#11]
for Prefixation v0.3.0

### Expected Behavior

The Prefixation Advancement tabs should show related advancements, or there shouldn't be advancements for this. They should definitely not crash the game.

### Current Behavior

Minecraft crashes when a Prefixation created advancement tab is clicked.

### Steps to Reproduce

1. get an item that has a prefix
2. an advancement should pop up. The advancement will be of the same name as the prefix.
3. go to the advancements menu
4. click on the advancement tab of the same name as the prefix

### Other notes

The crash log mentions extrautils2, but the game still crashes even after removing Extra Utilities 2.
The related fatal error seems to be 'Registering texture'.
 
crash log: https://pastebin.com/keHKBhqj

**Comment by MiningMark48** [comment]
Ok, thanks for finding. I'll look into this!

**Comment by MiningMark48** [comment]
**Dev Note:** The multiple advancement tabs should only be on one tab.

**Comment by paperclone22** [comment]
Oh btw I tested the mod on it's own, and it doesn't crash. But there seems to be a missing texture for the background of the advancement pages. My guess is that other mods were expecting something to be rendered, and crashed when there wasn't anything there to render

**Comment by MiningMark48** [comment]
That was my case also. I'm working on resolving the issue, this must've slipped by in testing.
