### ISSUE TITLE
Prefixes on chestplate only work in mainhand

### ISSUE THREAD

**Issue by paperclone22** [MiningMark48/Prefixation#13]
Edit: prefixation v0.3.2

### Expected Behavior

Chestplate prefixes should work when equipped in the chest slot as well as the main hand. 

### Current Behavior

Chestplate prefixes only work when held in the mainhand. They also don't register any armor points when in the chest slot, which makes non-prefixed chestplates better than prefixed ones

### Steps to Reproduce

1. craft a leather chestplate in a vanilla crafting table
2. equip the chestplate on the chest
3. equip the chestplate in the mainhand
4. compare steps 2 and 3

### Other notes

 
The data below is of a leather chestplate that I crafted. All instances of 'Slot:"mainhand"' should be replaced with 'Slot:"chest"'. These prefixes could also be duplicated to have prefixes for both mainhand and chest so that they would be consistant with vanilla enchantments.

{id:"minecraft:leather_chestplate",Count:1b,tag{prefix:"Heavy",prefix_index:4,type:"ARMOR",AttributeModifiers:[{UUIDMost:-3518070219318670797L,UUIDLeast:-5706401037796400898L,Amount:-0.015d,Slot:"mainhand",AttributeName:"generic.movementSpeed",Operation:0,Name:"generic.movementSpeed"},{UUIDMost:-8638070419312770545L,UUIDLeast:-95364110274640482L,Amount:2.0d,Slot:"mainhand",AttributeName:"generic.armorToughness",Operation:0,Name:"generic.armorToughness"},{UUIDMost:-43384964193124580773L,UUIDLeast:-23594160274648512L,Amount:2.0d,Slot:"mainhand",AttributeName:"generic.knockbackResistance",Operation:0,Name:"generic.knockbackResistance"}]},Damage:0s}

**Comment by MiningMark48** [comment]
Thanks for this, must have slipped by when redoing the prefix system. I'll get this fixed ASAP.
